import type { MediaAsset, Product } from "@/types/domain";

function createProductImages(prefix: string, altText: string): MediaAsset[] {
  return Array.from({ length: 4 }, (_, index) => ({
    id: `${prefix}-image-${index + 1}`,
    publicId: `loom-hearth/products/${prefix}-${index + 1}`,
    altText,
    sortOrder: index + 1,
    role: index === 0 ? ("hero" as const) : ("gallery" as const),
    mediaType: "image" as const,
    width: 1600,
    height: 1200,
  }));
}

export const launchProducts: Product[] = [
  {
    id: "rug-atlas-morning",
    type: "rug",
    slug: "atlas-morning",
    name: "Atlas Morning Rug",
    category: "rugs",
    description:
      "A hand-knotted Atlas rug with a warm sand field and terracotta detailing for living spaces that need softness and structure.",
    priceUsd: 1240,
    images: createProductImages("atlas-morning", "Atlas Morning Rug"),
    materials: ["Wool"],
    origin: "Morocco",
    status: "active",
    rugStyle: "atlas",
    dimensionsCm: {
      length: 250,
      width: 170,
    },
    weightKg: 9,
    fixedQuantity: 1,
    seoTitle: "Atlas Morning Rug",
    seoDescription: "Hand-knotted Atlas rug for the Loom & Hearth Studio launch collection.",
  },
  {
    id: "rug-terracotta-field",
    type: "rug",
    slug: "terracotta-field",
    name: "Terracotta Field Rug",
    category: "rugs",
    description:
      "A larger terracotta-toned rug with a dense woven field, selected for high-traffic spaces and statement layering.",
    priceUsd: 1480,
    images: createProductImages("terracotta-field", "Terracotta Field Rug"),
    materials: ["Wool", "Cotton"],
    origin: "Morocco",
    status: "active",
    rugStyle: "terracotta",
    dimensionsCm: {
      length: 290,
      width: 190,
    },
    weightKg: 11.5,
    fixedQuantity: 1,
    seoTitle: "Terracotta Field Rug",
    seoDescription: "Large handcrafted terracotta rug from the Loom & Hearth Studio launch collection.",
  },
  {
    id: "pouf-clay-knot",
    type: "multiUnit",
    slug: "clay-knot-pouf",
    name: "Clay Knot Pouf",
    category: "poufs",
    description:
      "A structured wool pouf with tonal clay striping, built for living-room seating, footrest use, or layered floor styling.",
    priceUsd: 220,
    images: createProductImages("clay-knot-pouf", "Clay Knot Pouf"),
    materials: ["Wool", "Cotton"],
    origin: "Morocco",
    status: "active",
    inventory: 12,
    lowStockThreshold: 3,
    variants: [
      {
        id: "pouf-clay-knot-sand",
        name: "Sand",
        sku: "POUF-CLAY-KNOT-SAND",
        inventory: 4,
      },
      {
        id: "pouf-clay-knot-clay",
        name: "Clay",
        sku: "POUF-CLAY-KNOT-CLAY",
        inventory: 5,
      },
      {
        id: "pouf-clay-knot-charcoal",
        name: "Charcoal",
        sku: "POUF-CLAY-KNOT-CHARCOAL",
        inventory: 3,
      },
    ],
    notifyMeEnabled: false,
    seoTitle: "Clay Knot Pouf",
    seoDescription: "Launch multi-unit pouf with color variants at Loom & Hearth Studio.",
  },
  {
    id: "pillow-hearth-stripe",
    type: "multiUnit",
    slug: "hearth-stripe-pillow",
    name: "Hearth Stripe Pillow",
    category: "pillows",
    description:
      "A striped accent pillow with warm neutral tones sized for sofas, lounge chairs, and layered bedding.",
    priceUsd: 96,
    images: createProductImages("hearth-stripe-pillow", "Hearth Stripe Pillow"),
    materials: ["Cotton"],
    origin: "Morocco",
    status: "active",
    inventory: 4,
    lowStockThreshold: 4,
    variants: [
      {
        id: "pillow-hearth-stripe-small",
        name: "Small",
        sku: "PILLOW-HEARTH-STRIPE-S",
        inventory: 1,
      },
      {
        id: "pillow-hearth-stripe-medium",
        name: "Medium",
        sku: "PILLOW-HEARTH-STRIPE-M",
        inventory: 2,
      },
      {
        id: "pillow-hearth-stripe-large",
        name: "Large",
        sku: "PILLOW-HEARTH-STRIPE-L",
        inventory: 1,
      },
    ],
    notifyMeEnabled: false,
    seoTitle: "Hearth Stripe Pillow",
    seoDescription: "Striped launch pillow with size variants at Loom & Hearth Studio.",
  },
  {
    id: "decor-cedar-vessel",
    type: "multiUnit",
    slug: "cedar-vessel",
    name: "Cedar Vessel Decor",
    category: "decor",
    description:
      "A sculptural vessel with a warm cedar-toned glaze intended for shelf styling and tabletop accents.",
    priceUsd: 84,
    images: createProductImages("cedar-vessel", "Cedar Vessel Decor"),
    materials: ["Ceramic"],
    origin: "Morocco",
    status: "active",
    inventory: 0,
    lowStockThreshold: 2,
    variants: [],
    notifyMeEnabled: true,
    seoTitle: "Cedar Vessel Decor",
    seoDescription: "Ceramic launch decor vessel from Loom & Hearth Studio.",
  },
  {
    id: "vintage-desert-find",
    type: "rug",
    slug: "desert-find",
    name: "Desert Find Vintage Piece",
    category: "vintage",
    description:
      "A one-of-one vintage textile piece selected for collectors who want an older handwoven statement with character.",
    priceUsd: 1680,
    images: createProductImages("vintage-desert-find", "Desert Find Vintage Piece"),
    materials: ["Wool"],
    origin: "Morocco",
    status: "active",
    rugStyle: "vintage",
    dimensionsCm: {
      length: 265,
      width: 175,
    },
    weightKg: 8.7,
    fixedQuantity: 1,
    seoTitle: "Desert Find Vintage Piece",
    seoDescription: "Vintage one-of-one launch textile from Loom & Hearth Studio.",
  },
];
